version: "3.8"
services:
  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile.local
    stdin_open: true
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
    working_dir: /go/src
    volumes:
      - ./src:/go/src
    ports:
      - "${APP_PORT}:${APP_PORT}"
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 1m
    tty: true
